// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"context"
	"github.com/gin-gonic/gin"
	"qqlx/base/app"
	"qqlx/base/conf"
	"qqlx/base/data"
	"qqlx/base/middleware"
	"qqlx/base/server"
	"qqlx/controller"
	"qqlx/pkg/permissions"
	"qqlx/router"
	"qqlx/service"
	"qqlx/store"
)

// Injectors from wire.go:

func InitApplication(ctx context.Context, cabinModelFile string) (*app.Application, func(), error) {
	db, cleanup, err := data.NewDB()
	if err != nil {
		return nil, nil, err
	}
	userStore := store.NewUserStore(db)
	generalRoleStore := store.NewRoleStore(db)
	client := data.CreateRDB(ctx)
	redis, cleanup2 := data.NewRedis(client)
	enforcer, err := permissions.InitCasbin(cabinModelFile)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	generalAuthorizStore := permissions.NewGeneralAuthorizStore(enforcer)
	userService := service.NewUserService(userStore, generalRoleStore, redis, generalAuthorizStore)
	userController := controller.NewUserController(userService)
	policyStore := store.NewPolicyStore(db)
	roleAssociationStore := store.NewRoleAssociationStore(db)
	roleService := service.NewRoleService(generalRoleStore, policyStore, roleAssociationStore, generalAuthorizStore)
	roleController := controller.NewRoleController(roleService)
	policyService := service.NewPolicyService(policyStore)
	policyController := controller.NewPolicyController(policyService)
	apiRoute := router.NewApiRoute(userController, roleController, policyController)
	authoriz := permissions.NewAuthoriz(enforcer)
	getUserStore := store.NewGetUserStore(userStore)
	authorizationMiddleware := middleware.NewAuthorization(redis, authoriz, getUserStore)
	engine := server.NewHttpServer(apiRoute, authorizationMiddleware)
	application := newApplication(engine)
	return application, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

const (
	Version = "1.0.0"
)

func newApplication(e *gin.Engine) *app.Application {
	return app.NewApp(app.WithName(conf.GetProjectName()), app.WithVersion(Version), app.WithServer(server.NewServer(e)))
}
